version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    container_name: ml_backend
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
    ports:
      - "5174:80"
    container_name: react_frontend
    depends_on:
      - backend
    restart: unless-stopped